name: neo_reusables
description: A Dart package for all Neo's reusables. It features mostly wrappers on already implemented Flutter widgets and other constructs to help you write better code.
version: 1.0.2
homepage: https://github.com/the-Jinxist/neo-reusables.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0





flutter:

  
  
  
  
  
  
  
  
  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
