name: Update Package

# The trigger for when we want this android-release ci to be executed
on:
  push:
    branches:
      - main

# Jobs we want to execute
jobs:

  # Job we want to run
  build-and-test:
    runs-on: ubuntu-latest

    # Steps to run
    steps:

      # Checkout the repository code using v1 of the standard checkout Action
    - uses: actions/checkout@v1
      
      # Use the standard Java Action to setup Java
      # With gives us a way to pass parameters to an action in this case: actions/setup-java@v1
    - uses: actions/setup-java@v1

      #Setting up dart
    - name: Setup Dart
      uses: dart-lang/setup-dart@v1

      # Analyzing project
    - name: Analyze Project Source
      run: dart analyze

      # Installing Pub Stuff
    - name: Install Pub Dependencies
      run: dart pub get
      with:
        # we want the latest Java 12
        java-version: '12.x'

      # Use the community Action to install Flutter
    - uses: subosito/flutter-action@v1
      with:
        # we want the stable channel
        flutter-version: '1.22.5'
        channel: 'stable'

    # Get Flutter Packages
    - name: Get All Flutter Packages
      run: flutter pub get

    # Build Yay!
    - name: Build Flutter APK
      run: flutter build apk

    # Update Package
    - name: Publish Update
      run: dart pub publish


